# Generated by Django 5.2.8 on 2025-11-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('competition', 'Competition / Olympiad'), ('project', 'Project'), ('volunteering', 'Volunteering'), ('leadership', 'Leadership'), ('sport_art', 'Sport / Art / Media'), ('other', 'Other')], default='other', max_length=30)),
                ('scale', models.CharField(choices=[('school', 'School'), ('city', 'City / Region'), ('national', 'National'), ('international', 'International')], default='school', max_length=30)),
                ('role_type', models.CharField(choices=[('participant', 'Participant'), ('winner', 'Winner / Prize'), ('organizer', 'Organizer'), ('leader', 'Leader / Founder')], default='participant', max_length=30)),
                ('duration_months', models.PositiveIntegerField(default=0)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ai_raw_response', models.JSONField(blank=True, null=True)),
                ('total_points', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
