# Generated by Django 5.2.8 on 2025-11-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_event_quest_shopitem_questcompletion_userpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='subcategory',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('research', 'Научно-исследовательская деятельность'), ('social', 'Социальная и волонтерская активность'), ('creative', 'Творческая деятельность'), ('sports', 'Спортивные достижения'), ('competence', 'Развитие компетенций'), ('other', 'Другое')], default='other', max_length=30),
        ),
    ]
