# Generated by Django 5.2.8 on 2025-11-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='soc_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
